### ISSUE TITLE
Billing Amount variable returning $0 in recurring reminder email

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-recurring-emails#29]
When !!billing_amount!! is added to the recurring reminder email, it's returning $0. Reports from users is this was working before December 2022.

Varialbe should be available in this email. (see line 190)
`"billing_amount"        => pmpro_formatPrice( $euser->membership_level->billing_amount ),`

Have recreated on live site: The sample had the same initial and recurring payment amount.

![reminder-template](https://user-images.githubusercontent.com/8083630/224726754-ebc95381-dc9b-4c53-9b6e-0603dc187838.png)

![reminder-email2](https://user-images.githubusercontent.com/8083630/224727739-0b13ed6d-a69c-400d-9f45-c9571a052fdf.png)

**Comment by MaximilianoRicoTabo** [comment]
Added this PR https://github.com/strangerstudios/pmpro-recurring-emails/pull/33 that fixes this issue @kimwhite

**Comment by dparker1005** [comment]
Closing as a PR was merged to resolve this issue in the next update
