### ISSUE TITLE
Notifications sent to memberships that already renewed

### ISSUE THREAD

**Issue by dananjohnson** [strangerstudios/pmpro-recurring-emails#4]
I activated this on a production site and it sent out its first round of notifications this morning. Almost everything worked fine, except it sent emails to two members whose subscriptions had already been automatically re-billed yesterday. Funnily, the message got the !!renewaldate!! variable correct, so it sent them warnings that they're memberships will renew in July 2017. Seems like maybe the DB query grabbed them based on the previous rebill date but didn't filter them out with the latest renewal?

The only modification I made to the plugin was to add a 30-day notification to the default 7-day.

Thanks for all the great work you do with PM Pro!

**Comment by ideadude** [comment]
I'm going to close this. I believe the latest version .5.1 fixes this. If you are still seeing problems, please open a new issue or get in touch. Thanks.
